[project]
name = "sublime-neytools"
version = "2.0.0"
description = "NeyTools for Sublime Text"
authors = [
    {name = "skether"}
]
requires-python = ">=3.14"

[dependency-groups]
dev = [
    "basedpyright>=1.39.10",
    "ruff>=0.16.4",
    "sublime-text-stubs>=1.4200.0b2",
]

[tool.ruff]
line-length = 300
indent-width = 4
exclude = ["**/__pycache__"]

[tool.ruff.lint]
preview = true
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # Pyflakes
    "I",  # isort
    "N",  # pep8-naming
    "B",  # flake8-bugbear
    "A",  # flake8-builtins
    "C4", # flake8-comprehensions
    "SIM",# flake8-simplify
    "UP", # pyupgrade
    "ANN",
]
ignore = ["UP015"]

[tool.basedpyright]
pythonVersion = "3.14"
include = ["."]
exclude = ["**/__pycache__"]
typeCheckingMode = "basic"
extraPaths = [
    "C:/Users/haran/AppData/Roaming/Sublime Text 3/Lib/python314",
]
venvPath = "."
venv = ".venv"
